config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'home/index'
  get 'tags/:tag', to: 'pictures#index', as: "tag"

  root to: 'home#index'

  resources :albums
  resources :pictures
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_many :pictures, dependent: :destroy

    validates :name, presence: true

    def first_image index
        @picture = Picture.where(album_id: index).first
        return @picture.image
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :user
    belongs_to :album, optional: true

    has_one_attached :image
    has_many :taggings
    has_many :tags, through: :taggings

    validate :image_type

    include PgSearch
    pg_search_scope :search_by_tag, against: [:all_tags]

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
      
    def all_tags
        self.tags.map(&:name).join(", ")
    end

    def self.tagged_with(name)
        Tag.find_by_name!(name).pictures
      end

    private
    def image_type
        if !image.attached?
            errors.add(:image, "please select images")
        else
            if !image.content_type.in?(%('image/jpeg' 'image/png'))
                errors.add(:image, 'needs to be a JPEG or PNG')
            end
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :pictures, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pictures, dependent: :destroy
  has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only: [:show, :destroy, :edit, :update]

    # GET albums/new
    def new
        @album = Album.new
    end

    # POST albums/new
    def create
        @album = Album.create(name: params[:album][:name], user_id: params[:album][:user_id])

        params[:album][:images].each do |img|
            Picture.create!(image: img, album_id: @album.id, user_id: params[:album][:user_id], 
            all_tags: params[:album][:all_tags])
        end

        respond_to do |format|
            if @album.save
                format.html { redirect_to root_path, notice: 'Album was successfully uploaded.' }
                format.json { render :index, status: :created, location: @album }
            else
                format.html { render :new }
                format.json { render json: @album.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET albums/:id
    def index
        if user_signed_in?
            @albums = current_user.albums.order(created_at: :desc)
        end
    end

    # GET albums/:id/pictures
    def show
        @pictures = Picture.where(album_id: @album.id)
    end

    # DELETE albums/:id
    def destroy
        @album.destroy

        respond_to do |format|
            format.html { redirect_to root_path, notice: 'Picture was successfully deleted.' }
            format.json { head :no_content }
        end
    end

    # GET albums/:id/edit
    def edit
    end

    # PUT albums/:id/
    def update
        @album.update(name: params[:album][:name])

        params[:album][:images].each do |img|
            Picture.create!(image: img, album_id: @album.id, user_id: params[:album][:user_id])
        end
        
        redirect_to album_path
    end

    private
        def album_params
            params.require(:album).permit(:user_id, :name, :all_tags, images: [])
        end

        def set_album
            @album = current_user.albums.find(params[:id])   
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @albums = current_user.albums.order(created_at: :desc)
      @pictures = current_user.pictures.order(created_at: :desc)
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :set_picture, only: [:destroy, :edit, :update]

    # GET pictures/new
    def new
        @picture = Picture.new
    end

    # POST pictures/new
    def create
        @picture = Picture.new(picture_params)

        if !picture_params[:album_id]
            @picture.album_id = nil
        end

        respond_to do |format|
            if @picture.save
                format.html { redirect_to root_path, notice: 'Picture was successfully uploaded.' }
                format.json { render :index, status: :created, location: @picture }
            else
                format.html { render :new }
                format.json { render json: @picture.errors, status: :unprocessable_entity }
            end
        end
    end

    # GET pictures/:id
    def index
        if user_signed_in?
            if params[:tag]
                @pictures = Picture.tagged_with(params[:tag])
            else
                @pictures = current_user.pictures.order(created_at: :desc)
            end
        end
    end

    # DELETE pictures/:id
    def destroy
        if @picture.album_id
            if Picture.where(album_id: @picture.album_id).count == 1
                @album = Album.where(id: @picture.album_id)
                @album.destroy(@picture.album_id)
            else
                @picture.destroy
            end
        else
            @picture.destroy
        end

        respond_to do |format|
            format.html { redirect_to root_path, notice: 'Picture was successfully deleted.' }
            format.json { head :no_content }
        end
    end

    # GET pictures/:id/edit
    def edit
    end

    private
        def set_picture
            @picture = current_user.pictures.find(params[:id])   
        end

        def picture_params
            params.require(:picture).permit(:user_id, :image, :album_id, :all_tags)
        end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def tag_links(tags)
        tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
    end
end

app/views/albums/_album_form.html.erb
<%= form_with(model: @album, local: true) do |form| %>
    <% if @album.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>
        
            <ul>
                <% @album.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= form.label "Name of Album" %>
        <%= form.text_field :name %>
    </div>

    <div class="form-group">
        <%= form.text_field :user_id, value: current_user.id, class:'d-none'%>
    </div>

    <div class="form-group">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true, :required => true %>
    </div>

    <div class="form-group">
        <%= form.label "Add tags" %>
        <%= form.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>

    <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
    </div>
    
<% end %>

app/views/albums/edit.html.erb
<h1>Update Album</h1>
  
<%= render 'album_form' %> 
  
<%= link_to "Back", root_url %> 

app/views/albums/index.html.erb
<% @albums.each do |album| %>
    <section class="album">
        <div class="metadata">
            <div class="date">
                <%= album.created_at %>
            </div>
        </div>
        <%= image_tag album.first_image(album.id), class: 'main-image' %>
        <div class="links">
            <h3><%= link_to album.name, album %></h3>
            <%= button_to 'Remove', album, method: :delete, data: { confirm: "Are you sure?" }%>
        </div>
    </section>
<% end %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'album_form' %>

<%= link_to 'Back', root_path %>

app/views/albums/show.html.erb
<div class = "links">
  <%= link_to 'Back', root_path, class: 'link' %>
  <%= link_to 'Upload new images', edit_album_path, class: 'link' %>
</div>

<h1><%= @album.name %></h1>

<div class="gallery" id="gallery">
  <% @pictures.each do |picture| %>
    <div class="mb-3 pics all 2">
        <%= image_tag picture.image.variant(resize: '500x500').processed, class: 'rounded gallery-image' %>
        <div class="caption">
            <ul class="metadata">
                <li><%= picture.image.metadata['width'] %> x <%= picture.image.metadata['height'] %></li>
                <li><%= picture.image.created_at %></li>
                <p><small>Tags: <%= raw picture.all_tags %></small</p>
            </ul>
            <%= button_to 'Remove', picture, method: :delete, data: { confirm: "Are you sure?" }%>
        </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <div class="nav-links">
        <%= link_to 'New Album', new_album_path, class: 'link' %>
        <%= link_to 'Upload File', new_picture_path, class: 'link' %><br>
    </div>
    <div class="albums">
        <%= render template: "albums/index" %>
    </div>
    <hr>
    <div class="albums">
        <%= render template: "pictures/index" %>
    </div>   
<% else %>
    <h1>Hi! Please sign in to continue.</h1>    
    <%= button_to "Sign in", new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= fa_stacked_icon "camera"%>
            Picha
          </a>
        </div>
        <div class="m-auto">
          <%= form_tag pictures_path, method: :get do %>
            <%= text_field_tag 'tag', params[:tag], placeholder: "Enter tag" %>
            <%= submit_tag 'Search!' %>
          <% end %>
        </div>
        <div class="user-section">
          <% if user_signed_in? %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= button_to "Sign in", new_user_session_path %>
          <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 620px;; padding-top: 20px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <p> © 2019 s278gupt </p>
      </nav>
    </footer>
  </body>
</html>

app/views/pictures/_picture_form.html.erb
<%= form_with(model: @picture, local: true) do |form| %>
    <% if @picture.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this album from being saved:</h2>
        
            <ul>
                <% @picture.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="form-group">
        <%= form.text_field :user_id, value: current_user.id, class:'d-none'%>
    </div>
    <div class="form-group">
        <%= form.label :image %>
        <%= form.file_field :image%>
    </div>
    <div class="form-group">
        <%= form.label "Add tags" %>
        <%= form.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>
    <div class="form-group">
        <%= form.submit class: "btn btn-primary" %>
    </div>
    
<% end %>

app/views/pictures/index.html.erb
<% @pictures.each do |picture| %>
    <section class="album">
        <div class="metadata">
            <div class="date">
                <%= picture.created_at %>
            </div>
        </div>
        <%= image_tag picture.image.variant(resize: '500x500').processed, class: 'main-image' %>
        <div class="links">
            <p><small>Tags: <%= raw tag_links(picture.all_tags) %></small</p>
            <%= button_to 'Remove', picture, method: :delete, data: { confirm: "Are you sure?" }%>
        </div>
    </section>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'picture_form' %>

<%= link_to 'Back', root_path %>